// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXrlVXFv1ysi2cVwOrmGBmDtFxS5ALmgY',
    appId: '1:565516938743:web:8dd905b9cf73dd03aad2f2',
    messagingSenderId: '565516938743',
    projectId: 'horas-v3-dc469',
    authDomain: 'horas-v3-dc469.firebaseapp.com',
    storageBucket: 'horas-v3-dc469.appspot.com',
    measurementId: 'G-YWW82N2WWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeamZXVkg_CAmck7fHQ4Z4a2nWV20XV5E',
    appId: '1:565516938743:android:49d93c6db8b2fc7aaad2f2',
    messagingSenderId: '565516938743',
    projectId: 'horas-v3-dc469',
    storageBucket: 'horas-v3-dc469.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGyQM5KETlGZsXlsiW3t3SXohjJ8obCOI',
    appId: '1:565516938743:ios:80c34739e1d0d443aad2f2',
    messagingSenderId: '565516938743',
    projectId: 'horas-v3-dc469',
    storageBucket: 'horas-v3-dc469.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGyQM5KETlGZsXlsiW3t3SXohjJ8obCOI',
    appId: '1:565516938743:ios:80c34739e1d0d443aad2f2',
    messagingSenderId: '565516938743',
    projectId: 'horas-v3-dc469',
    storageBucket: 'horas-v3-dc469.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXrlVXFv1ysi2cVwOrmGBmDtFxS5ALmgY',
    appId: '1:565516938743:web:d4af486f6ccfc80eaad2f2',
    messagingSenderId: '565516938743',
    projectId: 'horas-v3-dc469',
    authDomain: 'horas-v3-dc469.firebaseapp.com',
    storageBucket: 'horas-v3-dc469.appspot.com',
    measurementId: 'G-TB0904CXW3',
  );

}